GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs/
content-type: application/json
# There needs to be an empty line here!

{
    "author": "Azi blogger",
    "title": "Azis test blog",
    "url": "https://greatestblogtest.com",
    "likes": 1,
    "userId": "63834734432ab04978ab9f6f"
}

###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "azi",
    "password": "topsecret"
}

###
DELETE http://localhost:3001/api/persons/634b1318d59d357a8e89a52c

###
PUT http://localhost:3001/api/persons/634b0db19bf05ee82e3211d7
Content-Type: application/json

{
    "number": "777"
}
